name: TestActionsScript
'on': push
jobs:
  updateAuthor:
    runs-on: ubuntu-latest
    steps:
      - name: checking out code
        uses: actions/checkout@v2
      - name: extract git commit data
        uses: rlespinasse/git-commit-data-action@
      - name: Update author info
        run: 'echo ${{ env.GIT_COMMIT_AUTHOR_NAME }} > AUTHOR'
      - name: Raise PR
        uses: peter-evans/create-pull-request@
        with:
          branch: auto-pr-branch
          base: main
          title: demo for auto pr
          committer: >-
            ${{ env.GIT_COMMIT_AUTHOR_NAME }} <${{ env.GIT_COMMIT_AUTHOR_EMAIL
            }}">
          author: >-
            ${{ env.GIT_COMMIT_AUTHOR_NAME }} <${{ env.GIT_COMMIT_AUTHOR_EMAIL
            }}">
          body: This is to show automatic PR creation
          token: '${{ secrets.E6NP46ND8X }}'
          delete-branch: true
  autoapprove:
    name: Auto Approve a PR by dependabot
    needs: updateAuthor
    'on': pull_request
    runs-on: ubuntu-latest
    steps:
      - name: Auto approve
        uses: hmarr/auto-approve-action@v2.1.0
        if: >-
          github.actor == 'dependabot[bot]' || github.actor ==
          'dependabot-preview[bot]'
        with:
          github-token: '${{ secrets.E6NP46ND8X }}'
          pull-request-number: '${{ github.event.inputs.pullRequestNumber }}'
  automerge:
    name: Auto merge after successful checks
    needs: autoapprove
    runs-on: ubuntu-latest
    steps:
      - name: Auto merge
        uses: pascalgn/automerge-action@135f0bdb927d9807b5446f7ca9ecc2c51de03c4a
        if: >-
          github.actor == 'dependabot[bot]' || github.actor ==
          'dependabot-preview[bot]'
        env:
          GITHUB_TOKEN: '${{ secrets.E6NP46ND8X }}'
          MERGE_LABELS: dependencies
          MERGE_METHOD: rebase
  close-pull-request:
    name: Close Pull Request
    needs: automerge
    'on':
      pull_request_target:
        types:
          - opened
    runs-on: ubuntu-latest
    steps:
      - uses: superbrothers/close-pull-request@v3
        with: null
        comment: '[Close Pull Request]: test comment'
