name: TestActionsScript
on: push
jobs:
  createPullRequest:
    name: create-pull-request workflow
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Create report file
        run: date +%s > report.txt
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          token: '${{ secrets.E6NP46ND8X }}'
          commit-message: Add report file
          title: '[Example] Add report file'
          body: |
            This auto PR
          labels: 'report, automated pr'
  autoapprove:
    name: Auto approve PR
    needs: createPullRequest
    on: pull_request
    runs-on: ubuntu-latest
    steps:
      - name: Auto approve
        uses: hmarr/auto-approve-action@v2.1.0
        if: >-
          github.actor == 'dependabot[bot]' || github.actor ==
          'dependabot-preview[bot]'
        with:
          github-token: '${{ secrets.E6NP46ND8X }}'
          pull-request-number: '${{ github.event.inputs.pullRequestNumber }}'
  automerge:
    name: Auto merge after successful checks
    needs: autoapprove
    runs-on: ubuntu-latest
    steps:
      - name: Auto merge
        uses: pascalgn/automerge-action@135f0bdb927d9807b5446f7ca9ecc2c51de03c4a
        if: >-
          github.actor == 'dependabot[bot]' || github.actor ==
          'dependabot-preview[bot]'
        env:
          GITHUB_TOKEN: '${{ secrets.E6NP46ND8X }}'
          MERGE_LABELS: dependencies
          MERGE_METHOD: rebase
  close-pull-request:
    name: Close Pull Request
    needs: automerge
    on:
      pull_request_target:
        types:
          - opened
    runs-on: ubuntu-latest
    steps:
      - uses: superbrothers/close-pull-request@v3
        with: null
        comment: '[Close Pull Request]: test comment'
